/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { CustomersWhereUniqueInput } from "../../customers/base/CustomersWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { PaymentAccountsWhereUniqueInput } from "../../paymentAccounts/base/PaymentAccountsWhereUniqueInput";
import { EnumB2bTransactionsStatus } from "./EnumB2bTransactionsStatus";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";

@InputType()
class B2bTransactionsWhereInput {
  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  amount?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CustomersWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CustomersWhereUniqueInput)
  @IsOptional()
  @Field(() => CustomersWhereUniqueInput, {
    nullable: true,
  })
  customer?: CustomersWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => PaymentAccountsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PaymentAccountsWhereUniqueInput)
  @IsOptional()
  @Field(() => PaymentAccountsWhereUniqueInput, {
    nullable: true,
  })
  paymentAccount?: PaymentAccountsWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumB2bTransactionsStatus,
  })
  @IsEnum(EnumB2bTransactionsStatus)
  @IsOptional()
  @Field(() => EnumB2bTransactionsStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  transactionDate?: DateTimeNullableFilter;
}

export { B2bTransactionsWhereInput as B2bTransactionsWhereInput };
