/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { B2bTransactionsWhereInput } from "./B2bTransactionsWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { B2bTransactionsOrderByInput } from "./B2bTransactionsOrderByInput";

@ArgsType()
class B2bTransactionsFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => B2bTransactionsWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => B2bTransactionsWhereInput, { nullable: true })
  @Type(() => B2bTransactionsWhereInput)
  where?: B2bTransactionsWhereInput;

  @ApiProperty({
    required: false,
    type: [B2bTransactionsOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [B2bTransactionsOrderByInput], { nullable: true })
  @Type(() => B2bTransactionsOrderByInput)
  orderBy?: Array<B2bTransactionsOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { B2bTransactionsFindManyArgs as B2bTransactionsFindManyArgs };
