/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { B2bTransactionsCreateInput } from "./B2bTransactionsCreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateB2bTransactionsArgs {
  @ApiProperty({
    required: true,
    type: () => B2bTransactionsCreateInput,
  })
  @ValidateNested()
  @Type(() => B2bTransactionsCreateInput)
  @Field(() => B2bTransactionsCreateInput, { nullable: false })
  data!: B2bTransactionsCreateInput;
}

export { CreateB2bTransactionsArgs as CreateB2bTransactionsArgs };
