/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { B2bTransactionsWhereUniqueInput } from "./B2bTransactionsWhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { B2bTransactionsUpdateInput } from "./B2bTransactionsUpdateInput";

@ArgsType()
class UpdateB2bTransactionsArgs {
  @ApiProperty({
    required: true,
    type: () => B2bTransactionsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => B2bTransactionsWhereUniqueInput)
  @Field(() => B2bTransactionsWhereUniqueInput, { nullable: false })
  where!: B2bTransactionsWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => B2bTransactionsUpdateInput,
  })
  @ValidateNested()
  @Type(() => B2bTransactionsUpdateInput)
  @Field(() => B2bTransactionsUpdateInput, { nullable: false })
  data!: B2bTransactionsUpdateInput;
}

export { UpdateB2bTransactionsArgs as UpdateB2bTransactionsArgs };
