/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WaterTokensService } from "../waterTokens.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WaterTokensCreateInput } from "./WaterTokensCreateInput";
import { WaterTokens } from "./WaterTokens";
import { WaterTokensFindManyArgs } from "./WaterTokensFindManyArgs";
import { WaterTokensWhereUniqueInput } from "./WaterTokensWhereUniqueInput";
import { WaterTokensUpdateInput } from "./WaterTokensUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WaterTokensControllerBase {
  constructor(
    protected readonly service: WaterTokensService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WaterTokens })
  @nestAccessControl.UseRoles({
    resource: "WaterTokens",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: WaterTokensCreateInput,
  })
  async createWaterTokens(
    @common.Body() data: WaterTokensCreateInput
  ): Promise<WaterTokens> {
    return await this.service.createWaterTokens({
      data: data,
      select: {
        c2bTransactionId: true,
        charges: true,
        createdAt: true,
        deletedAt: true,
        expired: true,
        id: true,
        liters: true,
        tokenAmount: true,
        tokenRequests: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WaterTokens] })
  @ApiNestedQuery(WaterTokensFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WaterTokens",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async waterTokensItems(
    @common.Req() request: Request
  ): Promise<WaterTokens[]> {
    const args = plainToClass(WaterTokensFindManyArgs, request.query);
    return this.service.waterTokensItems({
      ...args,
      select: {
        c2bTransactionId: true,
        charges: true,
        createdAt: true,
        deletedAt: true,
        expired: true,
        id: true,
        liters: true,
        tokenAmount: true,
        tokenRequests: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WaterTokens })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WaterTokens",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async waterTokens(
    @common.Param() params: WaterTokensWhereUniqueInput
  ): Promise<WaterTokens | null> {
    const result = await this.service.waterTokens({
      where: params,
      select: {
        c2bTransactionId: true,
        charges: true,
        createdAt: true,
        deletedAt: true,
        expired: true,
        id: true,
        liters: true,
        tokenAmount: true,
        tokenRequests: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WaterTokens })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WaterTokens",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: WaterTokensUpdateInput,
  })
  async updateWaterTokens(
    @common.Param() params: WaterTokensWhereUniqueInput,
    @common.Body() data: WaterTokensUpdateInput
  ): Promise<WaterTokens | null> {
    try {
      return await this.service.updateWaterTokens({
        where: params,
        data: data,
        select: {
          c2bTransactionId: true,
          charges: true,
          createdAt: true,
          deletedAt: true,
          expired: true,
          id: true,
          liters: true,
          tokenAmount: true,
          tokenRequests: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WaterTokens })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WaterTokens",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWaterTokens(
    @common.Param() params: WaterTokensWhereUniqueInput
  ): Promise<WaterTokens | null> {
    try {
      return await this.service.deleteWaterTokens({
        where: params,
        select: {
          c2bTransactionId: true,
          charges: true,
          createdAt: true,
          deletedAt: true,
          expired: true,
          id: true,
          liters: true,
          tokenAmount: true,
          tokenRequests: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
