/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DocumentTypesService } from "../documentTypes.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DocumentTypesCreateInput } from "./DocumentTypesCreateInput";
import { DocumentTypes } from "./DocumentTypes";
import { DocumentTypesFindManyArgs } from "./DocumentTypesFindManyArgs";
import { DocumentTypesWhereUniqueInput } from "./DocumentTypesWhereUniqueInput";
import { DocumentTypesUpdateInput } from "./DocumentTypesUpdateInput";
import { DocumentsFindManyArgs } from "../../documents/base/DocumentsFindManyArgs";
import { Documents } from "../../documents/base/Documents";
import { DocumentsWhereUniqueInput } from "../../documents/base/DocumentsWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DocumentTypesControllerBase {
  constructor(
    protected readonly service: DocumentTypesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DocumentTypes })
  @nestAccessControl.UseRoles({
    resource: "DocumentTypes",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDocumentTypes(
    @common.Body() data: DocumentTypesCreateInput
  ): Promise<DocumentTypes> {
    return await this.service.createDocumentTypes({
      data: data,
      select: {
        code: true,
        createdAt: true,
        deletedAt: true,
        id: true,
        movement: true,
        name: true,
        requirePayment: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DocumentTypes] })
  @ApiNestedQuery(DocumentTypesFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DocumentTypes",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async documentTypesItems(
    @common.Req() request: Request
  ): Promise<DocumentTypes[]> {
    const args = plainToClass(DocumentTypesFindManyArgs, request.query);
    return this.service.documentTypesItems({
      ...args,
      select: {
        code: true,
        createdAt: true,
        deletedAt: true,
        id: true,
        movement: true,
        name: true,
        requirePayment: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DocumentTypes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DocumentTypes",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async documentTypes(
    @common.Param() params: DocumentTypesWhereUniqueInput
  ): Promise<DocumentTypes | null> {
    const result = await this.service.documentTypes({
      where: params,
      select: {
        code: true,
        createdAt: true,
        deletedAt: true,
        id: true,
        movement: true,
        name: true,
        requirePayment: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DocumentTypes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DocumentTypes",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDocumentTypes(
    @common.Param() params: DocumentTypesWhereUniqueInput,
    @common.Body() data: DocumentTypesUpdateInput
  ): Promise<DocumentTypes | null> {
    try {
      return await this.service.updateDocumentTypes({
        where: params,
        data: data,
        select: {
          code: true,
          createdAt: true,
          deletedAt: true,
          id: true,
          movement: true,
          name: true,
          requirePayment: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DocumentTypes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DocumentTypes",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDocumentTypes(
    @common.Param() params: DocumentTypesWhereUniqueInput
  ): Promise<DocumentTypes | null> {
    try {
      return await this.service.deleteDocumentTypes({
        where: params,
        select: {
          code: true,
          createdAt: true,
          deletedAt: true,
          id: true,
          movement: true,
          name: true,
          requirePayment: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/documentsItems")
  @ApiNestedQuery(DocumentsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Documents",
    action: "read",
    possession: "any",
  })
  async findDocumentsItems(
    @common.Req() request: Request,
    @common.Param() params: DocumentTypesWhereUniqueInput
  ): Promise<Documents[]> {
    const query = plainToClass(DocumentsFindManyArgs, request.query);
    const results = await this.service.findDocumentsItems(params.id, {
      ...query,
      select: {
        createdAt: true,
        deletedAt: true,

        documentType: {
          select: {
            id: true,
          },
        },

        documentableId: true,
        documentableType: true,
        id: true,
        numberField: true,
        paid: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/documentsItems")
  @nestAccessControl.UseRoles({
    resource: "DocumentTypes",
    action: "update",
    possession: "any",
  })
  async connectDocumentsItems(
    @common.Param() params: DocumentTypesWhereUniqueInput,
    @common.Body() body: DocumentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      documentsItems: {
        connect: body,
      },
    };
    await this.service.updateDocumentTypes({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/documentsItems")
  @nestAccessControl.UseRoles({
    resource: "DocumentTypes",
    action: "update",
    possession: "any",
  })
  async updateDocumentsItems(
    @common.Param() params: DocumentTypesWhereUniqueInput,
    @common.Body() body: DocumentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      documentsItems: {
        set: body,
      },
    };
    await this.service.updateDocumentTypes({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/documentsItems")
  @nestAccessControl.UseRoles({
    resource: "DocumentTypes",
    action: "update",
    possession: "any",
  })
  async disconnectDocumentsItems(
    @common.Param() params: DocumentTypesWhereUniqueInput,
    @common.Body() body: DocumentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      documentsItems: {
        disconnect: body,
      },
    };
    await this.service.updateDocumentTypes({
      where: params,
      data,
      select: { id: true },
    });
  }
}
