/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MeterTypes } from "./MeterTypes";
import { MeterTypesCountArgs } from "./MeterTypesCountArgs";
import { MeterTypesFindManyArgs } from "./MeterTypesFindManyArgs";
import { MeterTypesFindUniqueArgs } from "./MeterTypesFindUniqueArgs";
import { DeleteMeterTypesArgs } from "./DeleteMeterTypesArgs";
import { MeterTypesService } from "../meterTypes.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MeterTypes)
export class MeterTypesResolverBase {
  constructor(
    protected readonly service: MeterTypesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MeterTypes",
    action: "read",
    possession: "any",
  })
  async _meterTypesItemsMeta(
    @graphql.Args() args: MeterTypesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MeterTypes])
  @nestAccessControl.UseRoles({
    resource: "MeterTypes",
    action: "read",
    possession: "any",
  })
  async meterTypesItems(
    @graphql.Args() args: MeterTypesFindManyArgs
  ): Promise<MeterTypes[]> {
    return this.service.meterTypesItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MeterTypes, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MeterTypes",
    action: "read",
    possession: "own",
  })
  async meterTypes(
    @graphql.Args() args: MeterTypesFindUniqueArgs
  ): Promise<MeterTypes | null> {
    const result = await this.service.meterTypes(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MeterTypes)
  @nestAccessControl.UseRoles({
    resource: "MeterTypes",
    action: "delete",
    possession: "any",
  })
  async deleteMeterTypes(
    @graphql.Args() args: DeleteMeterTypesArgs
  ): Promise<MeterTypes | null> {
    try {
      return await this.service.deleteMeterTypes(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
