/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PersonalAccessTokens } from "./PersonalAccessTokens";
import { PersonalAccessTokensCountArgs } from "./PersonalAccessTokensCountArgs";
import { PersonalAccessTokensFindManyArgs } from "./PersonalAccessTokensFindManyArgs";
import { PersonalAccessTokensFindUniqueArgs } from "./PersonalAccessTokensFindUniqueArgs";
import { DeletePersonalAccessTokensArgs } from "./DeletePersonalAccessTokensArgs";
import { PersonalAccessTokensService } from "../personalAccessTokens.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PersonalAccessTokens)
export class PersonalAccessTokensResolverBase {
  constructor(
    protected readonly service: PersonalAccessTokensService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PersonalAccessTokens",
    action: "read",
    possession: "any",
  })
  async _personalAccessTokensItemsMeta(
    @graphql.Args() args: PersonalAccessTokensCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PersonalAccessTokens])
  @nestAccessControl.UseRoles({
    resource: "PersonalAccessTokens",
    action: "read",
    possession: "any",
  })
  async personalAccessTokensItems(
    @graphql.Args() args: PersonalAccessTokensFindManyArgs
  ): Promise<PersonalAccessTokens[]> {
    return this.service.personalAccessTokensItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PersonalAccessTokens, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PersonalAccessTokens",
    action: "read",
    possession: "own",
  })
  async personalAccessTokens(
    @graphql.Args() args: PersonalAccessTokensFindUniqueArgs
  ): Promise<PersonalAccessTokens | null> {
    const result = await this.service.personalAccessTokens(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PersonalAccessTokens)
  @nestAccessControl.UseRoles({
    resource: "PersonalAccessTokens",
    action: "delete",
    possession: "any",
  })
  async deletePersonalAccessTokens(
    @graphql.Args() args: DeletePersonalAccessTokensArgs
  ): Promise<PersonalAccessTokens | null> {
    try {
      return await this.service.deletePersonalAccessTokens(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
