/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ContractPartyService } from "../contractParty.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ContractPartyCreateInput } from "./ContractPartyCreateInput";
import { ContractParty } from "./ContractParty";
import { ContractPartyFindManyArgs } from "./ContractPartyFindManyArgs";
import { ContractPartyWhereUniqueInput } from "./ContractPartyWhereUniqueInput";
import { ContractPartyUpdateInput } from "./ContractPartyUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ContractPartyControllerBase {
  constructor(
    protected readonly service: ContractPartyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ContractParty })
  @nestAccessControl.UseRoles({
    resource: "ContractParty",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ContractPartyCreateInput,
  })
  async createContractParty(
    @common.Body() data: ContractPartyCreateInput
  ): Promise<ContractParty> {
    return await this.service.createContractParty({
      data: data,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        name: true,
        numberField: true,
        taxNumber: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ContractParty] })
  @ApiNestedQuery(ContractPartyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ContractParty",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async contractParties(
    @common.Req() request: Request
  ): Promise<ContractParty[]> {
    const args = plainToClass(ContractPartyFindManyArgs, request.query);
    return this.service.contractParties({
      ...args,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        name: true,
        numberField: true,
        taxNumber: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ContractParty })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContractParty",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async contractParty(
    @common.Param() params: ContractPartyWhereUniqueInput
  ): Promise<ContractParty | null> {
    const result = await this.service.contractParty({
      where: params,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        name: true,
        numberField: true,
        taxNumber: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ContractParty })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContractParty",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ContractPartyUpdateInput,
  })
  async updateContractParty(
    @common.Param() params: ContractPartyWhereUniqueInput,
    @common.Body() data: ContractPartyUpdateInput
  ): Promise<ContractParty | null> {
    try {
      return await this.service.updateContractParty({
        where: params,
        data: data,
        select: {
          createdAt: true,
          deletedAt: true,
          id: true,
          name: true,
          numberField: true,
          taxNumber: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ContractParty })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContractParty",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteContractParty(
    @common.Param() params: ContractPartyWhereUniqueInput
  ): Promise<ContractParty | null> {
    try {
      return await this.service.deleteContractParty({
        where: params,
        select: {
          createdAt: true,
          deletedAt: true,
          id: true,
          name: true,
          numberField: true,
          taxNumber: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
