/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MeterService } from "../meter.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MeterCreateInput } from "./MeterCreateInput";
import { Meter } from "./Meter";
import { MeterFindManyArgs } from "./MeterFindManyArgs";
import { MeterWhereUniqueInput } from "./MeterWhereUniqueInput";
import { MeterUpdateInput } from "./MeterUpdateInput";
import { CustomerMeterFindManyArgs } from "../../customerMeter/base/CustomerMeterFindManyArgs";
import { CustomerMeter } from "../../customerMeter/base/CustomerMeter";
import { CustomerMeterWhereUniqueInput } from "../../customerMeter/base/CustomerMeterWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MeterControllerBase {
  constructor(
    protected readonly service: MeterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Meter })
  @nestAccessControl.UseRoles({
    resource: "Meter",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMeter(@common.Body() data: MeterCreateInput): Promise<Meter> {
    return await this.service.createMeter({
      data: {
        ...data,

        meterType: data.meterType
          ? {
              connect: data.meterType,
            }
          : undefined,

        usages: data.usages
          ? {
              connect: data.usages,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        coordinates: true,
        createdAt: true,
        id: true,
        installationDate: true,

        meterType: {
          select: {
            id: true,
          },
        },

        status: true,
        tokenBalance: true,
        updatedAt: true,

        usages: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Meter] })
  @ApiNestedQuery(MeterFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Meter",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async meters(@common.Req() request: Request): Promise<Meter[]> {
    const args = plainToClass(MeterFindManyArgs, request.query);
    return this.service.meters({
      ...args,
      select: {
        coordinates: true,
        createdAt: true,
        id: true,
        installationDate: true,

        meterType: {
          select: {
            id: true,
          },
        },

        status: true,
        tokenBalance: true,
        updatedAt: true,

        usages: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Meter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Meter",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async meter(
    @common.Param() params: MeterWhereUniqueInput
  ): Promise<Meter | null> {
    const result = await this.service.meter({
      where: params,
      select: {
        coordinates: true,
        createdAt: true,
        id: true,
        installationDate: true,

        meterType: {
          select: {
            id: true,
          },
        },

        status: true,
        tokenBalance: true,
        updatedAt: true,

        usages: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Meter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Meter",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMeter(
    @common.Param() params: MeterWhereUniqueInput,
    @common.Body() data: MeterUpdateInput
  ): Promise<Meter | null> {
    try {
      return await this.service.updateMeter({
        where: params,
        data: {
          ...data,

          meterType: data.meterType
            ? {
                connect: data.meterType,
              }
            : undefined,

          usages: data.usages
            ? {
                connect: data.usages,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          coordinates: true,
          createdAt: true,
          id: true,
          installationDate: true,

          meterType: {
            select: {
              id: true,
            },
          },

          status: true,
          tokenBalance: true,
          updatedAt: true,

          usages: {
            select: {
              id: true,
            },
          },

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Meter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Meter",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMeter(
    @common.Param() params: MeterWhereUniqueInput
  ): Promise<Meter | null> {
    try {
      return await this.service.deleteMeter({
        where: params,
        select: {
          coordinates: true,
          createdAt: true,
          id: true,
          installationDate: true,

          meterType: {
            select: {
              id: true,
            },
          },

          status: true,
          tokenBalance: true,
          updatedAt: true,

          usages: {
            select: {
              id: true,
            },
          },

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/customerMeters")
  @ApiNestedQuery(CustomerMeterFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CustomerMeter",
    action: "read",
    possession: "any",
  })
  async findCustomerMeters(
    @common.Req() request: Request,
    @common.Param() params: MeterWhereUniqueInput
  ): Promise<CustomerMeter[]> {
    const query = plainToClass(CustomerMeterFindManyArgs, request.query);
    const results = await this.service.findCustomerMeters(params.id, {
      ...query,
      select: {
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,

        meterId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/customerMeters")
  @nestAccessControl.UseRoles({
    resource: "Meter",
    action: "update",
    possession: "any",
  })
  async connectCustomerMeters(
    @common.Param() params: MeterWhereUniqueInput,
    @common.Body() body: CustomerMeterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customerMeters: {
        connect: body,
      },
    };
    await this.service.updateMeter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/customerMeters")
  @nestAccessControl.UseRoles({
    resource: "Meter",
    action: "update",
    possession: "any",
  })
  async updateCustomerMeters(
    @common.Param() params: MeterWhereUniqueInput,
    @common.Body() body: CustomerMeterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customerMeters: {
        set: body,
      },
    };
    await this.service.updateMeter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/customerMeters")
  @nestAccessControl.UseRoles({
    resource: "Meter",
    action: "update",
    possession: "any",
  })
  async disconnectCustomerMeters(
    @common.Param() params: MeterWhereUniqueInput,
    @common.Body() body: CustomerMeterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customerMeters: {
        disconnect: body,
      },
    };
    await this.service.updateMeter({
      where: params,
      data,
      select: { id: true },
    });
  }
}
