/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { DocumentPaymentsListRelationFilter } from "../../documentPayments/base/DocumentPaymentsListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { PaymentChannelsListRelationFilter } from "../../paymentChannels/base/PaymentChannelsListRelationFilter";

@InputType()
class PaymentTypesWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  canSettle?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  deletedAt?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  displayName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => DocumentPaymentsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DocumentPaymentsListRelationFilter)
  @IsOptional()
  @Field(() => DocumentPaymentsListRelationFilter, {
    nullable: true,
  })
  documentPaymentsItems?: DocumentPaymentsListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  enabled?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PaymentChannelsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PaymentChannelsListRelationFilter)
  @IsOptional()
  @Field(() => PaymentChannelsListRelationFilter, {
    nullable: true,
  })
  paymentChannelsItems?: PaymentChannelsListRelationFilter;
}

export { PaymentTypesWhereInput as PaymentTypesWhereInput };
