/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { IssueTicketService } from "../issueTicket.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { IssueTicketCreateInput } from "./IssueTicketCreateInput";
import { IssueTicket } from "./IssueTicket";
import { IssueTicketFindManyArgs } from "./IssueTicketFindManyArgs";
import { IssueTicketWhereUniqueInput } from "./IssueTicketWhereUniqueInput";
import { IssueTicketUpdateInput } from "./IssueTicketUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class IssueTicketControllerBase {
  constructor(
    protected readonly service: IssueTicketService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: IssueTicket })
  @nestAccessControl.UseRoles({
    resource: "IssueTicket",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: IssueTicketCreateInput,
  })
  async createIssueTicket(
    @common.Body() data: IssueTicketCreateInput
  ): Promise<IssueTicket> {
    return await this.service.createIssueTicket({
      data: {
        ...data,

        appUser: data.appUser
          ? {
              connect: data.appUser,
            }
          : undefined,
      },
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [IssueTicket] })
  @ApiNestedQuery(IssueTicketFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "IssueTicket",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async issueTickets(@common.Req() request: Request): Promise<IssueTicket[]> {
    const args = plainToClass(IssueTicketFindManyArgs, request.query);
    return this.service.issueTickets({
      ...args,
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: IssueTicket })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IssueTicket",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async issueTicket(
    @common.Param() params: IssueTicketWhereUniqueInput
  ): Promise<IssueTicket | null> {
    const result = await this.service.issueTicket({
      where: params,
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: IssueTicket })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IssueTicket",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: IssueTicketUpdateInput,
  })
  async updateIssueTicket(
    @common.Param() params: IssueTicketWhereUniqueInput,
    @common.Body() data: IssueTicketUpdateInput
  ): Promise<IssueTicket | null> {
    try {
      return await this.service.updateIssueTicket({
        where: params,
        data: {
          ...data,

          appUser: data.appUser
            ? {
                connect: data.appUser,
              }
            : undefined,
        },
        select: {
          appUser: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: IssueTicket })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IssueTicket",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteIssueTicket(
    @common.Param() params: IssueTicketWhereUniqueInput
  ): Promise<IssueTicket | null> {
    try {
      return await this.service.deleteIssueTicket({
        where: params,
        select: {
          appUser: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
