/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MigrationsService } from "../migrations.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MigrationsCreateInput } from "./MigrationsCreateInput";
import { Migrations } from "./Migrations";
import { MigrationsFindManyArgs } from "./MigrationsFindManyArgs";
import { MigrationsWhereUniqueInput } from "./MigrationsWhereUniqueInput";
import { MigrationsUpdateInput } from "./MigrationsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MigrationsControllerBase {
  constructor(
    protected readonly service: MigrationsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Migrations })
  @nestAccessControl.UseRoles({
    resource: "Migrations",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMigrations(
    @common.Body() data: MigrationsCreateInput
  ): Promise<Migrations> {
    return await this.service.createMigrations({
      data: data,
      select: {
        createdAt: true,
        id: true,
        migrationName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Migrations] })
  @ApiNestedQuery(MigrationsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Migrations",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async migrationsItems(@common.Req() request: Request): Promise<Migrations[]> {
    const args = plainToClass(MigrationsFindManyArgs, request.query);
    return this.service.migrationsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        migrationName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Migrations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Migrations",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async migrations(
    @common.Param() params: MigrationsWhereUniqueInput
  ): Promise<Migrations | null> {
    const result = await this.service.migrations({
      where: params,
      select: {
        createdAt: true,
        id: true,
        migrationName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Migrations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Migrations",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMigrations(
    @common.Param() params: MigrationsWhereUniqueInput,
    @common.Body() data: MigrationsUpdateInput
  ): Promise<Migrations | null> {
    try {
      return await this.service.updateMigrations({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          migrationName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Migrations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Migrations",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMigrations(
    @common.Param() params: MigrationsWhereUniqueInput
  ): Promise<Migrations | null> {
    try {
      return await this.service.deleteMigrations({
        where: params,
        select: {
          createdAt: true,
          id: true,
          migrationName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
