/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LogsService } from "../logs.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LogsCreateInput } from "./LogsCreateInput";
import { Logs } from "./Logs";
import { LogsFindManyArgs } from "./LogsFindManyArgs";
import { LogsWhereUniqueInput } from "./LogsWhereUniqueInput";
import { LogsUpdateInput } from "./LogsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LogsControllerBase {
  constructor(
    protected readonly service: LogsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Logs })
  @nestAccessControl.UseRoles({
    resource: "Logs",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLogs(@common.Body() data: LogsCreateInput): Promise<Logs> {
    return await this.service.createLogs({
      data: {
        ...data,

        userId: data.userId
          ? {
              connect: data.userId,
            }
          : undefined,
      },
      select: {
        action: true,
        createdAt: true,
        deletedAt: true,
        id: true,
        ipAddress: true,
        message: true,
        requestPayload: true,
        resourceId: true,
        resourceModel: true,
        updateValues: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Logs] })
  @ApiNestedQuery(LogsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Logs",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async logsItems(@common.Req() request: Request): Promise<Logs[]> {
    const args = plainToClass(LogsFindManyArgs, request.query);
    return this.service.logsItems({
      ...args,
      select: {
        action: true,
        createdAt: true,
        deletedAt: true,
        id: true,
        ipAddress: true,
        message: true,
        requestPayload: true,
        resourceId: true,
        resourceModel: true,
        updateValues: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Logs })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Logs",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async logs(
    @common.Param() params: LogsWhereUniqueInput
  ): Promise<Logs | null> {
    const result = await this.service.logs({
      where: params,
      select: {
        action: true,
        createdAt: true,
        deletedAt: true,
        id: true,
        ipAddress: true,
        message: true,
        requestPayload: true,
        resourceId: true,
        resourceModel: true,
        updateValues: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Logs })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Logs",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLogs(
    @common.Param() params: LogsWhereUniqueInput,
    @common.Body() data: LogsUpdateInput
  ): Promise<Logs | null> {
    try {
      return await this.service.updateLogs({
        where: params,
        data: {
          ...data,

          userId: data.userId
            ? {
                connect: data.userId,
              }
            : undefined,
        },
        select: {
          action: true,
          createdAt: true,
          deletedAt: true,
          id: true,
          ipAddress: true,
          message: true,
          requestPayload: true,
          resourceId: true,
          resourceModel: true,
          updateValues: true,
          updatedAt: true,

          userId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Logs })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Logs",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLogs(
    @common.Param() params: LogsWhereUniqueInput
  ): Promise<Logs | null> {
    try {
      return await this.service.deleteLogs({
        where: params,
        select: {
          action: true,
          createdAt: true,
          deletedAt: true,
          id: true,
          ipAddress: true,
          message: true,
          requestPayload: true,
          resourceId: true,
          resourceModel: true,
          updateValues: true,
          updatedAt: true,

          userId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
